# This yaml configuration file stores parameters and constants for 
#
#      (1) executing the Snakemake data preprocessing pipeline (generates the files in BRIDGES_for_CA/Data) and
#      (2) the model itself.
#
# Changing this file leads to alternative BRIDGES models and therefore allows to analyze different scenarios. 
#
# Every entry should have a short one-line comment on its purpose and source.
#
# More detailed comments on the meaning of each parameter may be found in the parameter.jl file.


data_preprocessing:
    appliances:
    storage:
    transport:
        data-sets:
            # Data used to map California ZIP codes to California climate zones. Source: https://www.energy.ca.gov/programs-and-topics/programs/building-energy-efficiency-standards/climate-zone-tool-maps-and (January, 2024)
            zip-cz-matching: "https://www.energy.ca.gov/sites/default/files/2020-04/BuildingClimateZonesByZIPCode_ada.xlsx" # data used for comment, obtained from ()
            # Data used to estimate the number of vehicles by fuel type. Source: https://www.energy.ca.gov/files/zev-and-infrastructure-stats-data (January, 2024)
            vehicle-population: "https://www.energy.ca.gov/filebrowser/download/5432"
        constants:
        scenarios:
            transport_scenario_chargingtimer: "no_timer" # "with_timer", "no_timer"
            transport_scenario_chargeraccess: "LowHome_LowWork" # "UniversalHome", "HighHome", "LowHome_HighWork", "LowHome_LowWork"


params:
    foldername: "Data"

    ################################################################################
    ########### TOGGLES ###########
    # Turns on/off different model relaxations and functionality

    # Indicate whether you want to fix gas flow in the direction specified in the GasTransmission and ElecTransmission csv files (=0) or introduce binary variables to allow bi-directional flow directions (=1)
    GASFLOW_DIRECTIONS: 0

    # Indiciate whether gas distribution retirement should be contemplated (with the associated savings)
    gasdistretirement_allowed: 0
    gasdistretirement_forced: [0,0,0,0,0]
    region_retire: "All" # North, South, All, Cities

    # Indicate whether transmission expansion/retirement should be explicitly considered
    # 0 = No, 1 = Binary Yes, 2 = Continuous Yes Expansion Only (supports for elec-side expansion only)
    TRANSMISSION_EXPANSION_GAS: 0
    TRANSMISSION_EXPANSION_ELEC: 2

    # Indicate whether to include constraints that link representative time periods
    # for tracking storage state of charge (if = 0, periodicity constraints are imposed for each rep. period)
    LINKED_PERIODS_STORAGE: 1
    # for generator operations such as min up/down times and ramp rates (if = 0, constraints only apply within each rep. period)
    LINKED_PERIODS_GENOPS: 0

    # Indicate whether steady-state physics should be simulated for the electric and gas systems
    # If = 0, the flows of power and gas will be governed by simple transport models
    STEADYSTATE_ELEC: 1
    STEADYSTATE_GAS: 0

    appliance_decisions: 1                      # whether retired appliances may be replaced by appliances that satisfy same demand but with different fuel
    transport_decisions: 1                      # whether retired vehicles may be replaced by vehicles that satisfy same demand but with different fuel
    hybrids_allowed: 0
    bounding_steady_states: 0                   # default 0
    toggle_variableNatGasPrice: true
    force_retire_gasApps: 0
    allsector_emissions_constraint: 1
    # 1 = CARB aligned, 2 = beyond CARB, 3 = worse case
    consider_refrigerants: 1       # MUST set allsector_emissions_constraint = 1 too

    ################################################################################
    #### CLUSTERING PARAMETERS ####

    T_inv: 5                                    # Number of investment time periods modeled.
    N_Periods: 10                               # Number of representative operational time slices modeled for each investment period.
    HOURS_PER_PERIOD: 24                        # Number of hourly time steps in each rep. op. time slice

    HOURS_PER_YEAR: 8760                        # hours/year

    # Clustering technique to use for generating representative days
    # Options include:
    # (a) "average",
    # (b) "ward",
    # (c) "kmeans"
    clustering_case: "ward"
    consider_extremedays: "No"

    BaseYear: 2019                              # Initial year
    Years: [2025,2030,2035,2040,2045]           # Modeled investment years
    AllYears: [2019,2025,2030,2035,2040,2045]   # List of all calendar years

    ################################################################################
    #### CONVERSION CONSTANTS ####

    SEC_PER_HOUR: 3600                          # sec/hour
    MJ_PER_MWh: 3600                            # MJ/MWh
    MWh_PER_MMBTU: 0.293                        # MWh/MMBtu
    EF_NG: 0.181229                             # tCO2/MWh NG  This is "53.1/MWh_PER_MMBTU/1000". Per EPA emissions inventory (only CO2, no CH4 leakage)
    HHV_H2: 12.7                                # MJ/standard m3
    HHV_CH4: 37.7                               # MJ/standard m3
    LHV_H2: 10.24                               # MJ/standard m3
    LHV_CH4: 33.9                               # MJ/standard m3

    ## Gas/Power flow parameters
    SLACK_BUS: 20
    BASEMVA: 100
    SLACK_NODE: 20
    PRESSURE_MIN: 11.884429                     # This is (3447380/10^6)^2 and also 500 psi squared
    PRESSURE_MAX: 106.959777                    # This is (10342136/10^6)^2 and also 800 psi squared


    ################################################################################
    ######## CASE NAMING & ########
    ###### MODEL PARAMETERS #######

    # For file import, and to permit many sensitivity scenarios, each configuration can be specified by a system and a region which corresponds to the necessary import files
    system: "Network"
    region: "Cold"
    num: ""

    ### Biomethane
    biomethane: "Mid"
    max_biomethane_share_scenarios:             # Annual system-wide limitation on biomethane production (as a share of initial core gas demands)
        Low: 0.001
        Mid: 0.065
        High: 0.5      

    ### Industrials
    industrials: "None"                         # as % of baseline electricity demands
    baselinegasdemand_multiplier_scenarios:
        None: 1
        No: 0.001
        Mid: 2.5
        High: 5

    ### Energy Storage Cost
    # Li-ion
    costScenario_LiIon : "Mid"
    cost_LiIon_multiplier_scenarios:
        Low: 0.75
        Mid: 1
        High: 1.5

    # Fe-Air
    costScenario_FeAir: "Mid"
    cost_FeAir_multiplier_scenarios:
        Low: 0.75
        Mid: 1
        High: 1.53571   # corresponds to 21.5/14  # comparing both white papers from Form Energy

    # Hydrogen
    costScenario_HydrogenStorage: "Mid"
    cost_HydrogenStorage_multiplier_scenarios:
        Low: 0.75
        Mid: 1
        High: 3


    buildingretrofits: "Low"                    # "Low" or "High" cost of building retrofit
    transportretrofits: "Low"                   # "Low" or "High" cost of building retrofit

    CleanCosts: "Mid"
    cost_case: ""




    ### Offsets
    offsets_case: "NoOffsets"                   # where No offsets = 0, Unlimited Offsets = 1.0
    maxOffsets_elec: 0.0                        # % of gross emissions
    maxOffsets_gas: 0.0
    maxOffsets: 0.05
    initialEmissions: 115000000                    # tCO2

    offsets_Cost: [650, 500, 550, 500, 450]     # $/tCO2e  Alternative: [650, 550, 450, 350, 250], [1600, 1400, 1200, 1000, 800]  

    GasQuality: "Nodal"                         # "Annual", "No"

    br: 1.0                                     # build rate multiplier
    transmission_multiplier: 1.0                # electric transmission rating multiplier
    forceretire_multiplier: 1.0                 # multiplier for upper limit on appliance retirement (as share of natural retirement), min = 1.0


    ################################################################################
    ##### EMISSIONS INTENSITY #####

    # Specify emissions intensity targets for the electricity sector and gas sector with Slow and Fast sensitivity scenarios possible.
    # For reference, a natural gas-fired generator will yield ~500kg/MWh elec.; coal-fired generators will yield ~1000kg/MWh elec.; fossil natural gas delivered for direct-use will release ~181kg/MWh thermal

    EITrajectory: "MidEI"
    EI_ElecSector_scenarios:
        MidEI: [200,150,100,50,0]               # kg/MWh electricity generated #[500,250,75,50,0] [400,200,100,50,0]
        SlowEI: [500,500,250,250,0]             # kg/MWh electricity generated
        FastEI: [1000,500,100,10,0]             # kg/MWh electricity generated
    EI_GasSector_scenarios:
        MidEI: [200,150,100,50,0]               # kg/MWh gas delivered (to core customers) #[200,150,50,15,0]
        SlowEI: [200,200,90,90,0.0]             # kg/MWh gas delivered (to core customers)
        FastEI: [200,100,20,2,0.0]              # kg/MWh gas delivered (to core customers)
    TotalEmissions_Allowed: [218, 155, 110, 55, 0]   # total MMTCO2 from electricity generated AND gas delivered (to core customers) AND non-electric passenger vehicles. For only electricity and gas: [115, 80, 60, 30, 0]
    EC_TransportSector_scenarios:
        MidEI: [150,100,75,50,0]     # [103,75,50,25,0] emission constraint for transport sector in MMt_CO2 emitted annually by non-electric passenger vehicles (2022 in CA: 103e6 t)
        SlowEI: [103,100,75,30,0]   # emission constraint for transport sector in MMt_CO2 emitted annually by non-electric passenger vehicles (2022 in CA: 103e6 t)
        FastEI: [103,50,25,10,0]    # emission constraint for transport sector in MMt_CO2 emitted annually by non-electric passenger vehicles (2022 in CA: 103e6 t)

    H2molfrac_max: 0.0
    ADDITIONAL_SLACK_NODE: 18
    SLACK_GAS: 100000000                         # MW

    ################################################################################
    #### DISCOUNT RATES & WACC ####

    WACC: 0.07                                  # Weighted average cost of capital (WACC) applied to annualize utility-scale capital investments
    WACC_APPLIANCES: 0.15                       # Weighted average cost of capital (WACC) applied to annualize customer-scale appliance investments
    WACC_TRANSPORT: 0.15                        # Weighted average cost of capital (WACC) applied to annualize customer-scale vehicle investments
    societal_discounting: 0.05                  # discount rate [%] applied to discount future costs to present value
    LoadGrowthRate: 0.00                        # [%/year] of baseline electricity/gas demand growth 

    EndOfCostHorizon: 2050                      # Specifies the horizon over which societal costs should be included in objective function

    ################################################################################
    #### GAS DISTRIBUTION UTILITY FINANCIAL ASSUMPTIONS ####

    # Using a simplified set of financial assumptions
    equity: 0.10                                # return on equity afforded to utility shareholders [%]
    debt: 0.04                                  # interest rate on debt associated with securitization of the gas system  [%]
    shareFOM: 0.1                               # share of total annual revenue requirement that is fixed operating costs (as opposed to capital investment)
    ReinvestmentRate: 0.025                     # % of reinvestment 
    AvgDepreciation: 0.03                       # average % of depreciation per year

    # Cost of electric distribution infrastructure is based on (Fares, et. al, ) as a function of the peak electrical demand
    Cost_DistributionInfrastructure: 73        # $/kW peak 

    # Cost values for transmission expansion/retirement modeling
    ElecTransmissionCapitalCosts: 0.93          # $/MW-m from "Cost of long-distance energy transmission by different carriers," DeSantis
    ElecTransmissionOperatingCosts: 0.105       # $/MW   % of CAPEX where Misc. Costs per year = 5% of Total Capital Cost and Maintenance costs per year = 5% of Total Capital Cost
    GasTransmissionCapitalCosts: 0              # $/km
    GasTransmissionOperatingCosts: 0            # $/km

    ################################################################################
    #### FIRM GEN OPTIONS ####
    # nuclear retirement year 
    techScenario_Nuclear: "2030"
    # unrestricted
    nuclear_RetirementYear: 2060                   # normal retirement year, like all other generators
    # retirement by 2030 or 2045
    nuclear_RetirementYear_scenarios:
        2030: 2030
        2045: 2045

    techScenario_OffshoreWind: "Yes Offshore" # "No Offshore" activates restriction
    techScenario_NGCC: "No" # if "No" restricts to no new build of NG CC,CT,CC-CCS

    ################################################################################
    #### STORAGE OPTIONS ####

    ### Options: FormEnergy and PumpedHydroStorage and HydrogenStorage
    FormEnergy_allowed: 1
    PHS_allowed: 1
    H2Storage_allowed: 1
    # starting SOC
    SOC_fraction: 0.5

    nonGasHeat_ON: 1
    fraction_electrifiableHeat: 0.7       # 70 / 100
    simpleHeatElectrification_ON: 1   # simple == without heat storage
    ################################################################################
    #### TRANSPORT OPTIONS ####
    transport_scenario_zevmandate: "scoping_plan_bau" # "unconstrained", "scoping_plan", "scoping_plan_bau", "early", "late"
    transport_scenario_stockshare: "unconstrained" # "unconstrained", "early", "late"
    transport_scenario_vmt: "Scoping_Plan_BAU" # "EMMFAC", "Scoping_Plan_BAU", "Scoping_Plan_Proposed"
    transport_scenario_fuelcarbonintensity: "LCFS_current" # "EMFAC", "LCFS_current", "LCFS_proposed", "LCFS_alternative1", "LCFS_alternative2"
    transport_scenario_fueleconomy: "EMFAC" # "EMFAC"
    # In addition, the vehicle cost scenarios have to be changed in: CostScenarios.csv. Available: High, Mid, Low. For EVs in addition: ParityWithGas2030, ParityWithGas2035
